### ISSUE TITLE
Cameras not loading and home bridge restarts

### ISSUE THREAD

**Issue by Brandtley** [Brandawg93/homebridge-nest-cam2#24]
After upgrading to the lastest release when I try to select a individual camera in Apple Home I get a error message that there was “No response” this camera is not responding and Homebridge restarts.

**Comment by Brandawg93** [comment]
Can you run homebridge in debug mode and print out the response?

**Comment by Brandtley** [comment]
here is the error message when it crashes
[3/19/2020, 10:07:24 AM] TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:113:11)
    at normalizeSpawnArguments (child_process.js:398:3)
    at spawn (child_process.js:538:13)
    at NexusStreamer.setupFFMPEGPipe (/usr/local/lib/node_modules/homebridge-nest-cam2/lib/streamer.js:442:20)
    at NexusStreamer.startPlaybackWithRequest (/usr/local/lib/node_modules/homebridge-nest-cam2/lib/streamer.js:45:10)
    at NestCam.handleStreamRequest (/usr/local/lib/node_modules/homebridge-nest-cam2/lib/nestcam.js:236:18)
    at StreamController._handleStartStream (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:437:21)
    at StreamController._handleSelectedStreamConfigurationWrite (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:298:12)
    at Characteristic.SelectedRTPStreamConfiguration.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/StreamController.js:262:12)
    at Characteristic.SelectedRTPStreamConfiguration.emit (events.js:210:5)

**Comment by Brandawg93** [comment]
I think I know what the issue is. Possible fix coming soon.

**Comment by Brandawg93** [comment]
Can you try v1.1.9?

**Comment by Brandtley** [comment]
bingo... that seems to have fixed the issue.  Thanks for the quick response.
